### ISSUE TITLE
Regional pages' 24 hour weather table labeled last 2 days as 'today'

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#182]
Just added today's weather. Not doing an advisory. Labels for top two records both say 'today' on regional pages.

**Comment by jimurl** [comment]
Got it. I see why. To test whether to use 'Today' or the data 'Oct 21' , I have some logic that basically says IF this weather log is less than exactly 24 hours old, it is TODAY; otherwise the fule date.

If you entered the wx log yesterday at 9:00 , say, and then today's at 7:00. For those two hours, until 9:00 today, the second row of that table would say "Today" ( along with the first ).

I will change it to just loking at the date values: if today's data == the wx log date, call it 'Today'.
The only thing this will do, is that at 2am, 3am, etc, it will read 'Oct. whatever'., but who cares.
