### ISSUE TITLE
caught/buried/killed header on incidents page

### ISSUE THREAD

**Issue by amarienthal** [jimurl/gnfac-d6-d8#286]
can you remove the header that says "CAUGHT/BURIED/KILLED" on the incidents pages. 
https://www.mtavalanche.com/accident/18/01/02

It looked to me like that was the actual outcome. It should just show the words that are below that we enter e.g., '1 caught, 1 buried, 1 injured"

The "killed" part is what threw me off, and I could see it causing an uproar on the comment feed or email.

thanks

**Comment by jimurl** [comment]
Hey Alex, I removed that label, it makes more sense, as you said. 

I also re-arranged various of the fields on the accident report pages. I put the pdf first ( since y'all had a underlined message- click below for full report ), and the date and C/B/K/ Injured fields. 

Take a look and see how you like it and close the issue if it's good to go.

**Comment by amarienthal** [comment]
Jim, that looks good. Thanks. The only change would be to include the "synopsis" header above the paragraph that stands there. Otherwise, I like all the changes. THanks
